name:                mandelbrot
version:             0.1.0.0
github:              "b-mehta/mandelbrot"
license:             BSD3
author:              "Bhavik Mehta"
maintainer:          "bhavikmehta8@gmail.com"
copyright:           "2018 Bhavik Mehta"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/b-mehta/mandelbrot#readme>

dependencies:
- base >= 4.7 && < 5
- vector >= 0.12
- containers >= 0.5
- ansi-terminal >= 0.8
- JuicyPixels >= 3.2
- optparse-applicative >= 0.14
- ffmpeg-light >= 0.12.2.2

ghc-options:
  - -O2

source-dirs: src

executables:
  mandelbrot:
    source-dirs:         app
    main:                mandelbrot.hs
  mandelbrot-video:
    source-dirs:         app
    main:                mandelbrot-video.hs
